apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-elastic-users-csv
data:
  create-users.csv: |-
    username,fullname,password,roles
    marcos,marcos rosse,abcd123,marcos_role
    john,john doe,abcd123,john_role
    foo,foo bar,abcd123,foo_role
  delete-users.csv: |-
    username,fullname,password,roles
    marcos,marcos rosse,abcd123,marcos_role
    john,john doe,abcd123,john_role
    foo,foo bar,abcd123,foo_role
  